<?xml version="1.0" encoding="utf-8"?><Database Name="yeensnhi_mydb" Class="MyDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql.bsite.net\MSSQL2016;Initial Catalog=yeensnhi_mydb;User ID=yeensnhi_mydb" SettingsObjectName="PerfumeShared.Properties.Settings" SettingsPropertyName="yeensnhi_mydbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Perfume" Member="Perfumes">
    <Type Name="Perfume">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Origin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>